name: Michael Rotolo
markdown: kramdown
plugins:
  - jekyll-seo-tag
title: Michael Rotolo
description: Michael &ldquo;Chip&rdquo; Rotolo is a Research Associate at Pew Research Center in Washington, DC. His research examines the interplay of religion, morality, and politics in the United States.
url: https://mrotolo.com
twitter:
  username: mrotolo1
  card: summary
