name: Michael Rotolo
markdown: kramdown
plugins:
  - jekyll-seo-tag
title: Michael Rotolo
description: Michael Rotolo is a Ph.D. candidate and University Presidential Fellow in the Department of Sociology at Notre Dame. His research focuses on morality, values, religion, culture, politics, aspirations, and cognition, especially among young Americans and in the context of families.
url: https://mrotolo.com
twitter:
  username: mrotolo1
  card: summary
